name: collab_vm_server_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.3 <3.0.0'

dev_dependencies:
  image: ^4.0.10
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dart_rfb: ^0.7.0
  sqlite3: ^1.9.1